import Head from "next/head";
import { ReactNode } from "react";
import Header from "./Header";

type LayoutProps = {
  children: ReactNode;
  title?: string;
  className?: string;
};

function Layout({ children, title, className }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{`Blog ${title}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={className}>{children}</div>
    </>
  );
}

export default Layout;
